### ISSUE TITLE
Incorrect end of line handling inside string literals

### ISSUE THREAD

**Issue by sharwell** [sharwell/webtools.sourceediting.xpath#39]
Currently the **Literals003** test is failing because the CRLF line ending inside of the string literal is being preserved as a CRLF by `LiteralUtils.unquote`. According to §A.2.3, this should actually be read as a single LF instead.

**Comment by sharwell** [comment]
Duplicate of #20

**Comment by RackerWilliams** [comment]
Looks good 👍
